# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details

version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ContainerSolutions/externalsecret-operator

jobs:
  test:
    executor: go
    steps:
      - checkout
      - run: make test
      - run: make coverage

  push:
    executor: go
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: make build
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: DOCKER_TAG=latest make push

workflows:
  version: 2
  build:
    jobs:
      - test
      - push:
          requires:
            - test
          filters:
            branches:
              only: push
