version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ContainerSolutions/externalsecret-operator
    steps:
      - checkout
      - run: make test
      - run: make coverage

  push:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ContainerSolutions/externalsecret-operator
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: make build
      - run: DOCKER_TAG=latest make push

workflows:
  version: 2
  build:
    jobs:
      - test
      - push:
          requires:
            - test
          filters:
            branches:
              only: push
