version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"      
    steps:
      - checkout
      - run: make test
      - run: make coverage

  push:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: make build
      - run: make push

workflows:
  version: 2
  build:
    jobs:
      - test
      - push:
          requires:
            - test
