# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ContainerSolutions/externalsecret-operator
    steps:
      - checkout
      - run: make test
      - run: make coverage
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ContainerSolutions/externalsecret-operator
    steps:
      - run: make build
      - run: make push
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


workflows:
  version: 2
  build:
    jobs:
      - build:
          requires:
            - test
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: push

