version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ContainerSolutions/externalsecret-operator
    steps:
      - checkout
      - run: make test
      - run: make coverage

  push-latest:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/ContainerSolutions/externalsecret-operator
    environment:
      DOCKER_TAG: latest
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: make build
      - run: make push

workflows:
  version: 2
  build:
    jobs:
      - test
      - push-latest:
          requires:
            - test
          filters:
            branches:
              only: push
