apiVersion: apps/v1
kind: Deployment
metadata:
  name: externalconfig-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: externalconfig-operator
  template:
    metadata:
      labels:
        name: externalconfig-operator
    spec:
      containers:
        - name: externalconfig-operator
          image: containersol/externalconfig-operator:0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - externalconfig-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "externalconfig-operator"
