
apiVersion: apps/v1
kind: Deployment
metadata:
  name: externalsecret-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: externalsecret-operator
  template:
    metadata:
      labels:
        name: externalsecret-operator
    spec:
      containers:
        - name: externalsecret-operator
          image: ${DOCKER_IMAGE}:${DOCKER_TAG}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - externalsecret-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "externalsecret-operator"
            - name: AWS_ACCESS_KEY_ID
              value: ${AWS_ACCESS_KEY_ID}
            - name: AWS_SECRET_ACCESS_KEY
              value: ${AWS_SECRET_ACCESS_KEY}
            - name: AWS_REGION
              value: ${AWS_REGION}
